import { useEffect, useState } from "react";
import { Check, Code2, Save, Sparkles } from "lucide-react";
import { getFallbackSiteContent, SiteContentRecord, supabase } from "@/lib/supabase";

type Props = { setMessage: (message: string) => void };
const sectionMeta = [["identity", "Identity & About", "Hero, bio, focus areas", "01"], ["skills", "Skills", "Tools and learning groups", "02"], ["journey", "Journey", "Timeline entries", "03"], ["certifications", "Certifications", "Proof and credential links", "04"], ["contact", "Contact & Links", "Social destinations and email", "05"]] as const;

export default function SiteContentEditor({ setMessage }: Props) {
  const [items, setItems] = useState<SiteContentRecord[]>(getFallbackSiteContent());
  const [saved, setSaved] = useState<Record<string, boolean>>({});
  const [loading, setLoading] = useState(true);
  useEffect(() => { if (!supabase) { setLoading(false); return; } supabase.from("portfolio_site_content").select("key,value").order("key").then(({ data, error }) => { if (error) setMessage(`Content table unavailable: ${error.message}`); else if (data?.length) setItems(data as SiteContentRecord[]); setLoading(false); }); }, [setMessage]);
  const update = (key: string, value: string) => { setItems((current) => current.map((item) => item.key === key ? { ...item, value } : item)); setSaved((current) => ({ ...current, [key]: false })); };
  const format = (item: SiteContentRecord) => { try { update(item.key, JSON.stringify(JSON.parse(item.value), null, 2)); setMessage(`${item.label} formatted.`); } catch { setMessage(`${item.label} has invalid JSON. Fix the highlighted content before formatting.`); } };
  const save = async (item: SiteContentRecord) => { if (!supabase) return; let value: unknown; try { value = JSON.parse(item.value); } catch { setMessage(`${item.label} must contain valid JSON before saving.`); return; } const { error } = await supabase.from("portfolio_site_content").upsert({ key: item.key, value, updated_at: new Date().toISOString() }); if (error) setMessage(error.message); else { setSaved((current) => ({ ...current, [item.key]: true })); setMessage(`${item.label} is live and saved.`); } };
  if (loading) return <section className="admin-showcase"><p className="admin-showcase-loading">Loading live section editors…</p></section>;
  return <section className="admin-showcase site-content-studio" id="site-content-editor"><div className="studio-banner"><div><p className="admin-kicker"><Sparkles size={13} /> LIVE CONTENT STUDIO</p><h2>Every section,<br /><em>under control.</em></h2><p>Update the content model for any public section. Changes are protected by Supabase Auth and saved directly to the live database.</p></div><span className="studio-live-pill"><i /> DATABASE ONLINE</span></div><div className="editor-grid">{sectionMeta.map(([key, label, detail, number]) => { const item = items.find((entry) => entry.key === key) || { key, label, value: "{}" }; return <article className="content-editor-card" id={key} key={key}><header><span className="editor-number">{number}</span><div><h3>{label}</h3><p>{detail}</p></div><span className="editor-status"><i /> LIVE</span></header><div className="editor-toolbar"><span><Code2 size={13} /> JSON content model</span><button type="button" onClick={() => format(item)}>Format JSON</button></div><textarea aria-label={`${label} content JSON`} value={item.value} onChange={(event) => update(key, event.target.value)} spellCheck={false} /><footer><small>Keep the field names intact so the public layout renders correctly.</small><button type="button" className={`admin-save ${saved[key] ? "is-saved" : ""}`} onClick={() => save(item)}>{saved[key] ? <><Check size={14} /> Saved live</> : <><Save size={14} /> Save {label}</>}</button></footer></article>; })}</div></section>;
}
