import { useEffect, useState } from "react";
import { Check, Plus, Save, Sparkles, Trash2 } from "lucide-react";
import { getFallbackSiteContent, SiteContentRecord, supabase } from "@/lib/supabase";

type Props = { setMessage: (message: string) => void };
type AnyRecord = Record<string, any>;
const meta = [["identity", "Identity & About", "Hero, about copy, and profile tags", "01"], ["skills", "Skills", "Skill groups and individual tools", "02"], ["journey", "Journey", "Timeline milestones", "03"], ["certifications", "Certifications", "Credentials, issuers, and links", "04"], ["contact", "Contact & Links", "Social destinations and email", "05"]] as const;

function read(item: SiteContentRecord): AnyRecord { if (item.value && typeof item.value === "object") return item.value as AnyRecord; try { return JSON.parse(item.value) as AnyRecord; } catch { return {}; } }
function setValue(items: SiteContentRecord[], key: string, value: AnyRecord) { return items.map((item) => item.key === key ? { ...item, value: JSON.stringify(value, null, 2) } : item); }

export default function SiteContentEditor({ setMessage }: Props) {
  const [items, setItems] = useState<SiteContentRecord[]>(getFallbackSiteContent());
  const [saved, setSaved] = useState<Record<string, boolean>>({});
  const [editing, setEditing] = useState<Record<string, boolean>>({ identity: true, skills: true, journey: true, certifications: true, contact: true });
  const [loading, setLoading] = useState(true);
  useEffect(() => { if (!supabase) { setLoading(false); return; } Promise.all([supabase.from("portfolio_site_content").select("key,value").order("key"), supabase.from("portfolio_certifications").select("id,title,caption,issuer,issue_date,credential_url,sort_order").order("sort_order")]).then(([contentResult, certificationResult]) => { if (contentResult.error) setMessage(`Content table unavailable: ${contentResult.error.message}`); const fallback = Object.fromEntries(getFallbackSiteContent().map((item) => [item.key, read(item)])); const rows = (contentResult.data || []) as SiteContentRecord[]; const merged = rows.map((item) => { const live = read(item); const base = fallback[item.key] || {}; if (item.key === "identity") Object.assign(live, base, live); if (item.key === "contact") Object.assign(live, base, live); if (item.key === "skills") live.groups = [...(live.groups || []), ...(base.groups || []).filter((group: AnyRecord) => !(live.groups || []).some((current: AnyRecord) => current.title === group.title))]; if (item.key === "journey") live.entries = [...(live.entries || []), ...(base.entries || []).filter((entry: AnyRecord) => !(live.entries || []).some((current: AnyRecord) => current.title === entry.title))]; if (item.key === "certifications") { const legacy = (certificationResult.data || []).map((cert: AnyRecord) => ({ title: cert.title, issuer: cert.issuer || "", issue_date: cert.issue_date || "", credential_url: cert.credential_url || "", caption: cert.caption || "" })); live.entries = [...legacy, ...(live.entries || []).filter((entry: AnyRecord) => !legacy.some((current: AnyRecord) => current.title === entry.title))]; } return { ...item, value: JSON.stringify(live, null, 2) }; }); setItems(merged.length ? merged : getFallbackSiteContent()); setLoading(false); }); }, [setMessage]);
  const update = (key: string, value: AnyRecord) => { setItems((current) => setValue(current, key, value)); setSaved((current) => ({ ...current, [key]: false })); };
  const save = async (item: SiteContentRecord) => { if (!supabase) return; const { error } = await supabase.from("portfolio_site_content").upsert({ key: item.key, value: read(item), updated_at: new Date().toISOString() }); if (error) setMessage(error.message); else { setSaved((current) => ({ ...current, [item.key]: true })); setMessage(`${item.label} is live and saved.`); } };
  const deleteSection = async (item: SiteContentRecord) => { if (!supabase || !window.confirm(`Delete all ${item.label} content? This will clear it from the public portfolio.`)) return; const empty: AnyRecord = item.key === "identity" ? { hero: "", bio: "", about: "", tags: [] } : item.key === "skills" ? { groups: [] } : item.key === "journey" || item.key === "certifications" ? { entries: [] } : { github: "", linkedin: "", email: "", instagram: "", twitter: "" }; const { error } = await supabase.from("portfolio_site_content").upsert({ key: item.key, value: empty, updated_at: new Date().toISOString() }); if (error) setMessage(error.message); else { setItems((current) => setValue(current, item.key, empty)); setMessage(`${item.label} deleted from the public portfolio.`); } };
  const field = (label: string, value: string, onChange: (value: string) => void, multiline = false) => <label className="structured-field">{label}{multiline ? <textarea rows={4} value={value || ""} onChange={(event) => onChange(event.target.value)} /> : <input value={value || ""} onChange={(event) => onChange(event.target.value)} />}</label>;
  const actions = (item: SiteContentRecord) => <footer className="structured-footer"><small>Changes are saved to the live Supabase content table.</small><button type="button" className={`admin-save ${saved[item.key] ? "is-saved" : ""}`} onClick={() => save(item)}>{saved[item.key] ? <><Check size={14} /> Saved live</> : <><Save size={14} /> Save {item.label}</>}</button></footer>;
  const addButton = (label: string, onClick: () => void) => <button type="button" className="structured-add" onClick={onClick}><Plus size={14} /> {label}</button>;
  if (loading) return <section className="admin-showcase"><p className="admin-showcase-loading">Loading live section editors…</p></section>;
  return <section className="admin-showcase site-content-studio" id="site-content-editor"><div className="studio-banner"><div><p className="admin-kicker"><Sparkles size={13} /> LIVE CONTENT STUDIO</p><h2>Every section,<br /><em>under control.</em></h2><p>Edit each public section with dedicated fields. Add as many skills, journey entries, and certifications as you need.</p></div><span className="studio-live-pill"><i /> DATABASE ONLINE</span></div><div className="structured-editor-list">{meta.map(([key, label, detail, number]) => { const item = items.find((entry) => entry.key === key) || { key, label, value: "{}" }; const value = read(item); return <article className={`structured-editor-card ${editing[key] ? "is-editing" : "is-locked"}`} id={key} key={key}><header><span className="editor-number">{number}</span><div><h3>{label}</h3><p>{detail}</p></div><span className="editor-status"><i /> LIVE</span><div className="section-actions"><button type="button" className="section-edit" onClick={() => setEditing((current) => ({ ...current, [key]: !current[key] }))}>{editing[key] ? "Done" : "Edit"}</button><button type="button" className="section-delete" onClick={() => deleteSection(item)}><Trash2 size={13} /> Delete</button></div></header><div className="structured-body">
    {key === "identity" && <><div className="structured-grid">{field("Hero headline", value.hero, (next) => update(key, { ...value, hero: next }))}{field("About / bio", value.bio, (next) => update(key, { ...value, bio: next }), true)}</div>{field("About details", value.about, (next) => update(key, { ...value, about: next }), true)}{field("Profile tags, comma separated", (value.tags || []).join(", "), (next) => update(key, { ...value, tags: next.split(",").map((tag: string) => tag.trim()).filter(Boolean) }))}{actions(item)}</>}
    {key === "skills" && <>{(value.groups || []).map((group: AnyRecord, index: number) => <div className="repeatable-row" key={`skill-${index}`}><div className="repeatable-heading"><strong>Skill group {String(index + 1).padStart(2, "0")}</strong><button type="button" className="structured-delete" onClick={() => update(key, { ...value, groups: value.groups.filter((_: AnyRecord, i: number) => i !== index) })}><Trash2 size={14} /> Remove</button></div><div className="structured-grid">{field("Label", group.label, (next) => { const groups = [...value.groups]; groups[index] = { ...group, label: next }; update(key, { ...value, groups }); })}{field("Group title", group.title, (next) => { const groups = [...value.groups]; groups[index] = { ...group, title: next }; update(key, { ...value, groups }); })}</div>{field("Skills, comma separated", (group.items || []).join(", "), (next) => { const groups = [...value.groups]; groups[index] = { ...group, items: next.split(",").map((skill: string) => skill.trim()).filter(Boolean) }; update(key, { ...value, groups }); })}</div>)}{addButton("Add skill group", () => update(key, { ...value, groups: [...(value.groups || []), { label: String((value.groups || []).length + 1).padStart(2, "0"), title: "New skill group", items: [] }] }))}{actions(item)}</>}
    {key === "journey" && <>{(value.entries || []).map((entry: AnyRecord, index: number) => <div className="repeatable-row" key={`journey-${index}`}><div className="repeatable-heading"><strong>Timeline entry {String(index + 1).padStart(2, "0")}</strong><button type="button" className="structured-delete" onClick={() => update(key, { ...value, entries: value.entries.filter((_: AnyRecord, i: number) => i !== index) })}><Trash2 size={14} /> Remove</button></div><div className="structured-grid">{field("Year / label", entry.year, (next) => { const entries = [...value.entries]; entries[index] = { ...entry, year: next }; update(key, { ...value, entries }); })}{field("Title", entry.title, (next) => { const entries = [...value.entries]; entries[index] = { ...entry, title: next }; update(key, { ...value, entries }); })}</div>{field("Description", entry.text, (next) => { const entries = [...value.entries]; entries[index] = { ...entry, text: next }; update(key, { ...value, entries }); }, true)}</div>)}{addButton("Add journey entry", () => update(key, { ...value, entries: [...(value.entries || []), { year: "Next", title: "New milestone", text: "Describe this chapter…" }] }))}{actions(item)}</>}
    {key === "certifications" && <>{(value.entries || []).map((entry: AnyRecord, index: number) => <div className="repeatable-row" key={`cert-${index}`}><div className="repeatable-heading"><strong>Certification {String(index + 1).padStart(2, "0")}</strong><button type="button" className="structured-delete" onClick={() => update(key, { ...value, entries: value.entries.filter((_: AnyRecord, i: number) => i !== index) })}><Trash2 size={14} /> Remove</button></div><div className="structured-grid">{field("Certificate title", entry.title, (next) => { const entries = [...value.entries]; entries[index] = { ...entry, title: next }; update(key, { ...value, entries }); })}{field("Issuer", entry.issuer, (next) => { const entries = [...value.entries]; entries[index] = { ...entry, issuer: next }; update(key, { ...value, entries }); })}{field("Issue date", entry.issue_date, (next) => { const entries = [...value.entries]; entries[index] = { ...entry, issue_date: next }; update(key, { ...value, entries }); })}{field("Credential URL", entry.credential_url, (next) => { const entries = [...value.entries]; entries[index] = { ...entry, credential_url: next }; update(key, { ...value, entries }); })}</div>{field("Caption", entry.caption, (next) => { const entries = [...value.entries]; entries[index] = { ...entry, caption: next }; update(key, { ...value, entries }); }, true)}</div>)}{addButton("Add certification", () => update(key, { ...value, entries: [...(value.entries || []), { title: "New certification", issuer: "", issue_date: "", credential_url: "", caption: "" }] }))}{actions(item)}</>}
    {key === "contact" && <><div className="structured-grid">{field("GitHub", value.github, (next) => update(key, { ...value, github: next }))}{field("LinkedIn", value.linkedin, (next) => update(key, { ...value, linkedin: next }))}{field("Email", value.email, (next) => update(key, { ...value, email: next }))}{field("Instagram", value.instagram, (next) => update(key, { ...value, instagram: next }))}{field("X / Twitter", value.twitter, (next) => update(key, { ...value, twitter: next }))}</div>{actions(item)}</>}
  </div></article>; })}</div></section>;
}
